name:                foomake
version:             0.1.0.0
synopsis:            Why not make CMake build configurations more declarative?
description:         See README file
homepage:            http://github.com/laserpants/foomake#readme
license:             BSD3
author:              Heikki Johannes Hildén
maintainer:          hildenjohannes@gmail.com
category:            Configuration
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: lib
  dependencies:
  - aeson >= 1.3 && < 2
  - bytestring >= 0.10 && < 1
  - text >= 1.2 && < 2
  - unordered-containers >= 0.2.9 && < 1
  - yaml >= 0.8 && < 1

executables:
  foomake:
    source-dirs:      src
    main:             Main.hs
    dependencies:
    - aeson >= 1.3 && < 2
    - bytestring >= 0.10 && < 1
    - foomake
    - yaml >= 0.8 && < 1

tests:
  foomake-test:
    main:             Main.hs
    source-dirs:      test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson >= 1.3 && < 2
    - bytestring >= 0.10 && < 1
    - foomake
    - hspec >= 2.5 && < 3
    - text >= 1.2 && < 2
    - unordered-containers >= 0.2.9 && < 1
    - yaml >= 0.8 && < 1
